# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Utilities.xcworkspace -scheme Utilities-Example -sdk iphonesimulator -destination 'id=34FA4749-C467-4D45-9F8E-E31AEDDC39C2' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
