# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -workspace Example/Utilities.xcworkspace -scheme "Utilities-Example" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
- pod lib lint